---
- hosts: all
  gather_facts: no
  vars:
  - x: ""
  tasks:
  - name: Wait for the vms to load
    local_action: wait_for host={{ inventory_hostname }} port=5985 state=drained delay=0 timeout=1200  
  - name: Wait for stable state
    local_action: wait_for host={{ inventory_hostname }} port=5985 state=drained delay=10 timeout=300
  - name: Get IP
    raw: ipconfig
    register: x
  - name: Print Output
    debug: var=x
