---
- hosts: all
  gather_facts: no
  vars:
  - x: ""
  tasks:
  - name: Wait for the vms to load
    local_action: wait_for host={{ inventory_hostname }} port=5985 state=drained delay=0 timeout=1200  
  - name: Wait 2 minutes
    pause: seconds=2
  - name: Wait for the vms to load 2
    local_action: wait_for host={{ inventory_hostname }} port=5985 state=drained delay=0 timeout=1200  
  - name: Get IP
    raw: ipconfig
    register: x
    until: x.rc == 0
    retries: 10
    delay: 5

  - name: Print Output
    debug: var=x
